// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQ6kHE2EsTiC4gBNAyw2Gtnb57laN8PqQ',
    appId: '1:993814511606:web:1542a974d8421cd876d1d7',
    messagingSenderId: '993814511606',
    projectId: 'taxi-app-flutter-249db',
    authDomain: 'taxi-app-flutter-249db.firebaseapp.com',
    storageBucket: 'taxi-app-flutter-249db.appspot.com',
    measurementId: 'G-RCR79NE19X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKZSUq-Y6K0oH6EYbwKmuWFunNhofVrqk',
    appId: '1:993814511606:android:65f9891627716b5076d1d7',
    messagingSenderId: '993814511606',
    projectId: 'taxi-app-flutter-249db',
    storageBucket: 'taxi-app-flutter-249db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCR-vsYEfsEKwgavxCoyLQdSNNcVA26KrE',
    appId: '1:993814511606:ios:fbdbe9d92e1edb3476d1d7',
    messagingSenderId: '993814511606',
    projectId: 'taxi-app-flutter-249db',
    storageBucket: 'taxi-app-flutter-249db.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCR-vsYEfsEKwgavxCoyLQdSNNcVA26KrE',
    appId: '1:993814511606:ios:e10f159230b2ec4776d1d7',
    messagingSenderId: '993814511606',
    projectId: 'taxi-app-flutter-249db',
    storageBucket: 'taxi-app-flutter-249db.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
